name: "release-test"
on:
  release:
    types: [created]

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nelsonsilva/setup-k3s@v0.1.0
    - uses: ./
      with:
        repo: https://chartmuseum.platform.dev.nuxeo.com
        chart: nuxeo
    - name: Testing
      run: |
        kubectl get pods